/** @format */
import Head from "next/head";
import variable from "@/styles/variables.module.scss";
import NavOtherPage from "@/components/NavOtherPage";
import LamutClinic from "@/components/LamutClinic";

export default function Home() {
	return (
		<>
			<Head>
				<title>Lamut, Ifugao Clinic</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={variable.main}>
				<NavOtherPage />
				<LamutClinic />
			</main>
		</>
	);
}
