/** @format */
import Head from "next/head";
import variable from "../../styles/variables.module.scss";
import NavOtherPage from "@/components/NavOtherPage";
import Clinics from "@/components/Clinics";

export default function Home() {
	return (
		<>
			<Head>
				<title>Clinics</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={variable.main}>
				<NavOtherPage />
				<Clinics />
			</main>
		</>
	);
}
